version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    depends_on:
      - mysql
    restart: on-failure
    build:
      context: ../$CONTEXT_FOLDER
      dockerfile: Dockerfile
    ports:
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mysql_data:
